### PR TITLE
Topic Style improved.

### PR DESCRIPTION
**Pull request by pupboss**
- Topic Style improved.
- About page cell add deselectRowAtIndexPath method.
- About page remove useless footer line.

### CODE REVIEW

**Comment by klesh** [comment]
Hi, Jay, I couldn't build and run after merging. I might be caused by cocoapods version? Any advise will be appreciated. Thanks

qq20160309-0

**Comment by pupboss** [comment]
Please try rolling back the Podfile.lock file, I committed it by mistake yesterday...

Replace the 39~41 lines with "COCOAPODS: 0.39.0"

I'm so sorry

**Comment by pupboss** [comment]
In CocoaPods version 1.0.0, dependencies in Podfile must be limited in a target, it seems like this:

```
target 'CNode' do
pod 'Alamofire'
...
end
```

I had the mistaken idea that only Podfile has changed, so I didn't check the Podfile.lock file.

I clone the repo again just now, and `pod install` successfully. Good luck :-)

**Comment by klesh** [comment]
Hi, I've upgraded my CocoaPods to 1.0-beta4, can you make a pull request for Podfile? so I can test. BTW, my xcode now complains about these missing files: Pods-CNode.debug.xcconfig and Pods-CNode.release.xcconfig under CNode/Pods folder. I think you might need to push those files as well.

**Comment by pupboss** [comment]
I tested again, nothing goes wrong, here is my steps:

```
cd Desktop/
git clone https://github.com/pupboss/cnodejs-swift.git
cd Desktop/cnodejs-swift/
```

Do some changes to Profile like this

```
target 'CNode' do
pod 'Alamofire'
...
end
```

```
Updating local specs repositories

CocoaPods 1.0.0.beta.5 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.0.0.beta.5

Analyzing dependencies
Downloading dependencies
Installing APParallaxHeader (0.1.6)
Installing Alamofire (3.1.4)
Installing Kingfisher (1.9.0)
Installing MMDrawerController (0.6.0)
Installing PureLayout (3.0.1)
Installing SwiftDate (2.0.2)
Installing SwiftyJSON (2.3.2)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `CNode.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 7 dependencies from the Podfile and 7 total
pods installed.
```

I'll make the pull request later

**Comment by pupboss** [comment]
What's more, the user login part always got a crash, it never worked since my first compilation

**Comment by pupboss** [comment]
And, I didn't see the `Pods-CNode.debug.xcconfig` file anywhere, the only changed file is Podfile

**Pull request merged**
